### ISSUE TITLE
ca load error

### ISSUE THREAD

**Issue by liberwang1013** [clux/kube-rs#45]
~/.kube/config content
```
apiVersion: v1
clusters:
- cluster:
    server: https://<api-server>:8443
  name: <cluster_name>
contexts:
- context:
    cluster: <cluster_name>
    namespace: default
    user: ops/<cluster_name>
  name: default/<cluster_name>/ops
current-context: default/<cluster_name>/ops
kind: Config
preferences: {}
users:
- name: ops/<cluster_name>
  user:
    token: <token>
```

backtrace infomation
```
thread 'main' panicked at 'failed to load kubernetes config: ErrorMessage { msg: "Failed to get data/file with base64 format" }

stack backtrace:
   0: backtrace::backtrace::libunwind::trace::h8de4fdf219a770b7 (0x107ad819d)
             at /Users/liber/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.32/src/backtrace/libunwind.rs:88
      backtrace::backtrace::trace_unsynchronized::ha6afc095d9332ab9
             at /Users/liber/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.32/src/backtrace/mod.rs:66
   1: backtrace::backtrace::trace::h4fac325b7e05066a (0x107ad8123)
             at /Users/liber/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.32/src/backtrace/mod.rs:53
   2: backtrace::capture::Backtrace::create::h7b587b6a1d993b62 (0x107acbc47)
             at /Users/liber/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.32/src/capture.rs:165
   3: backtrace::capture::Backtrace::new_unresolved::h34e2772506327d29 (0x107acbbc8)
             at /Users/liber/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.32/src/capture.rs:159
   4: failure::backtrace::internal::InternalBacktrace::new::hb9d17a2bf6aee8db (0x107ac9940)
             at /Users/liber/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
   5: failure::backtrace::Backtrace::new::h1031a9f1486e8c9a (0x107aca7ef)
             at /Users/liber/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
   6: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h7e1a433a37ac03a7 (0x107503b6d)
             at /Users/liber/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19
   7: <failure::error::Error as core::convert::From<F>>::from::hcb6d1cf3345130d1 (0x1074d7f88)
             at /Users/liber/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36
   8: failure::error_message::err_msg::h19bb9fd7e57228fe (0x107502de0)
             at /Users/liber/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12
   9: kube::config::utils::data_or_file_with_base64::hb84a4552025028d7 (0x107500f2f)
             at /Users/liber/.cargo/registry/src/github.com-1ecc6299db9ec823/kube-0.10.0/src/config/utils.rs:34
  10: kube::config::apis::Cluster::load_certificate_authority::h73c27af072a2c87f (0x1074bed0b)
             at /Users/liber/.cargo/registry/src/github.com-1ecc6299db9ec823/kube-0.10.0/src/config/apis.rs:118
  11: kube::config::kube_config::KubeConfigLoader::ca::h7e4f13e496e7b9e9 (0x1074fd83d)
             at /Users/liber/.cargo/registry/src/github.com-1ecc6299db9ec823/kube-0.10.0/src/config/kube_config.rs:59
  12: kube::config::load_kube_config::h076b913f2d127e18 (0x1074e2689)
             at /Users/liber/.cargo/registry/src/github.com-1ecc6299db9ec823/kube-0.10.0/src/config/mod.rs:47
  13: controller::main::hd20ffe3bd6b3e6cb (0x10749d396)
             at src/main.rs:22
  14: std::rt::lang_start::{{closure}}::ha8e06417b2f85ecb (0x10749d202)
             at /rustc/5d20ff4d2718c820632b38c1e49d4de648a9810b/src/libstd/rt.rs:64
  15: {{closure}} (0x107cec488)
             at src/libstd/rt.rs:49
      do_call<closure,i32>
             at src/libstd/panicking.rs:293
  16: __rust_maybe_catch_panic (0x107cf059f)
             at src/libpanic_unwind/lib.rs:85
  17: try<i32,closure> (0x107cecf6e)
             at src/libstd/panicking.rs:272
      catch_unwind<closure,i32>
             at src/libstd/panic.rs:388
      lang_start_internal
             at src/libstd/rt.rs:48
  18: std::rt::lang_start::hfac9a9dfbdf902c2 (0x10749d1e2)
             at /rustc/5d20ff4d2718c820632b38c1e49d4de648a9810b/src/libstd/rt.rs:64
  19: controller::main::hd20ffe3bd6b3e6cb (0x10749d482)', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/5d20ff4d2718c820632b38c1e49d4de648a9810b/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::expect
             at /rustc/5d20ff4d2718c820632b38c1e49d4de648a9810b/src/libcore/result.rs:827
  10: controller::main
             at src/main.rs:22
  11: std::rt::lang_start::{{closure}}
             at /rustc/5d20ff4d2718c820632b38c1e49d4de648a9810b/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  14: std::panicking::update_count_then_panic
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/5d20ff4d2718c820632b38c1e49d4de648a9810b/src/libstd/rt.rs:64
  16: controller::main
```

my certifcate authority is not private, so there is no ca info in *~/.kube/config*

**Comment by clux** [comment]
Yeah, there's no support for advanced kube configs at the moment. See #19 

When developing locally, I suggest [impersonating a service account](https://clux.github.io/probes/post/2019-03-31-impersonating-kube-accounts/) for now.

**Comment by clux** [comment]
Better config support in 0.13.0. You might have more luck now.

**Comment by clux** [comment]
Closing. Lots of work went into this in earlier versions. Please reopen if it persists.
